import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import {
  MdButtonModule,
  MdCheckboxModule,
  // MdCoreModule,
  MdCardModule,
  MdIconModule,
  MdLineModule,
  MdListModule,
  MdMenuModule,
  MdTabsModule,
  MdChipsModule,
  MdInputModule,
  MdRadioModule,
  MdCommonModule,
  MdDialogModule,
  MdOptionModule,
  MdRippleModule,
  MdSelectModule,
  MdSliderModule,
  MdSidenavModule,
  MdToolbarModule,
  MdTooltipModule,
  MdGridListModule,
  MdSnackBarModule,
  MdDatepickerModule,
  MdNativeDateModule,
  MdProgressBarModule,
  MdSlideToggleModule,
  MdAutocompleteModule,
  MdButtonToggleModule,
  MdProgressSpinnerModule
} from '@angular/material';

@NgModule({
  imports: [
    MdButtonModule,
    MdCheckboxModule,
    // MdCoreModule,
    MdCardModule,
    MdIconModule,
    MdLineModule,
    MdListModule,
    MdMenuModule,
    MdTabsModule,
    MdChipsModule,
    MdInputModule,
    MdRadioModule,
    MdCommonModule,
    MdDialogModule,
    MdOptionModule,
    MdRippleModule,
    MdSelectModule,
    MdSliderModule,
    MdSidenavModule,
    MdToolbarModule,
    MdTooltipModule,
    MdGridListModule,
    MdSnackBarModule,
    MdDatepickerModule,
    MdNativeDateModule,
    MdProgressBarModule,
    MdSlideToggleModule,
    MdAutocompleteModule,
    MdButtonToggleModule,
    MdProgressSpinnerModule
],
  exports: [
    MdButtonModule,
    MdCheckboxModule,
    // MdCoreModule,
    MdCardModule,
    MdIconModule,
    MdLineModule,
    MdListModule,
    MdMenuModule,
    MdTabsModule,
    MdChipsModule,
    MdInputModule,
    MdRadioModule,
    MdCommonModule,
    MdDialogModule,
    MdOptionModule,
    MdRippleModule,
    MdSelectModule,
    MdSliderModule,
    MdSidenavModule,
    MdToolbarModule,
    MdTooltipModule,
    MdGridListModule,
    MdSnackBarModule,
    MdDatepickerModule,
    MdNativeDateModule,
    MdProgressBarModule,
    MdSlideToggleModule,
    MdAutocompleteModule,
    MdButtonToggleModule,
    MdProgressSpinnerModule
],
  declarations: []
})
export class MaterialModuleModule { }
